Charte
Association-Mallouestan/docs.mallouestan.github.io pull request #39
Opened 2024-01-17 10:09 UTC by Charlobb

2024-01-17 10:21 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +- Utiliser l'argent des boîtes dans l'espace commun (courses, sanctuaire, essence) ;
enlever essence

2024-01-17 10:21 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +- Un·e visiteus·e est responsable de ses actes et gestes sur le lieu. Il ou elle est maîtresse de son quotidien et responsable de la communication avec l'ensemble du collectif.
remplacer "la communication" par "sa communication"

2024-01-17 10:25 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +
Toute personne qui quitte définitivement le lieu perd de fait ses droits et son statut

2024-01-17 10:37 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +
-proposition de ne pas mentionner l'argent de poche (fluctuant) 
-ajouter une ligne : Un budget concernant les besoins essentiels est assuré pour les personnes membres et discuté collectivement

2024-01-17 10:47 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +### Membre
nouvel intitulé

LES ARRIMES

2024-01-17 10:51 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +qui cherche à créer une façon saine de vivre. Nos positions et valeurs ne sont pas dépendantes d'une romantisation du passé ou d'une indépendance absolue. Elles sont le fruit d'un travail critique, b
problème début de phrase

2024-01-17 10:52 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +- **antispécisme**
rajouter un note de bas de page

2024-01-17 11:26 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +Nous nous reconnaissons dans l'anarcho-communisme, notamment par notre opposition aux hiérarchies artificielles (non justifiées), à l'État, à l'argent et à la propriété privée, ainsi qu'à l'importanc
Il s'agit d'inscrire une rupture avec l'anarchisme d'aujourd'hui qui est un anarchisme individualiste.

2024-01-17 11:27 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +Nous nous reconnaissons dans l'anarcho-communisme, notamment par notre opposition aux hiérarchies artificielles (non justifiées), à l'État, à l'argent et à la propriété privée, ainsi qu'à l'importanc
et libérale.

2024-01-17 11:29 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +Nous nous reconnaissons dans l'anarcho-communisme, notamment par notre opposition aux hiérarchies artificielles (non justifiées), à l'État, à l'argent et à la propriété privée, ainsi qu'à l'importanc
Il s'agit d'inscrire une rupture avec un anarchisme souvent représenté de façon individualiste et libérale.

2024-01-17 11:43 UTC, CortneyKnorr requested changes

2024-01-17 11:43 UTC, CortneyKnorr commented on Charte et annexes/Manuel des visiteuses Mallouestanaises.md
>  ## Préface
Mise à jour avec la nouvelle charte complète

2024-01-17 11:48 UTC, CortneyKnorr commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +- Utiliser l'argent des boîtes dans l'espace commun (courses, sanctuaire, essence) ;
C'est fait

2024-01-17 12:20 UTC, CortneyKnorr commented
Correction othograaphique

2024-01-17 14:33 UTC, CortneyKnorr commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +- De mutualiser ses ressources (comme précisé à la section mutualisation des ressources) en excluant un minimum nécessaire à maintenir une autonomie vis-à-vis du collectif (ce minimum est fixé au mom
Ajout de la responsabilité de s'assurer de la présence d'au moin un résidents

2024-01-17 14:36 UTC, CortneyKnorr commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +- De mutualiser ses ressources (comme précisé à la section mutualisation des ressources) en excluant un minimum nécessaire à maintenir une autonomie vis-à-vis du collectif (ce minimum est fixé au mom
au moin un arrimé plutot

2024-02-06 10:00 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +- De mutualiser ses ressources (comme précisé à la section mutualisation des ressources) en excluant un minimum nécessaire à maintenir une autonomie vis-à-vis du collectif (ce minimum est fixé au mom
Cadrer pour qu'une présence en tout temps ne soit pas obligtoire. Peut-être qq chose comme s'assurer de la présence d'au moins un-e arrimé-e pour assurer les taches qui leur sont propres ?

2024-02-06 10:03 UTC, Charlobb commented on Charte et annexes/Manuel des chercheuses Mallouestanaises.md
> +- De mutualiser ses ressources (comme précisé à la section mutualisation des ressources) en excluant un minimum nécessaire à maintenir une autonomie vis-à-vis du collectif (ce minimum est fixé au mom
(Lau)

2024-02-10 19:25 UTC, CortneyKnorr commented
Checker la charte visiteuse

2024-02-21 18:48 UTC, CortneyKnorr approved these changes

2024-02-21 18:49 UTC, CortneyKnorr submitted a review, later dismissed

2024-02-21 18:57 UTC, LauTbk approved these changes
Tout bon pour moi

2024-02-25 17:04 UTC, LemuRien1312 approved these changes

2024-02-28 11:11 UTC, CortneyKnorr approved these changes

2024-02-28 11:17 UTC, merged